version: "3.8"

services:
  web:
    image: your-dockerhub-username/my-resume:latest # Change to your actual image name
    ports:
      - "80:80"
    networks:
      - my-network

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - my-network

  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
    networks:
      - my-network
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    networks:
      - my-network

volumes:
  jenkins_home:
